version: '3'
services:
  web:
    container_name: o-q-le-agora
    build: .
    environment:
      - CONNECTIONSTRING=mongodb://db:27017
    ports:
     - "4000:4000"
    volumes:
     - .:/go/src/app
    depends_on:
      - db
  db:
    image: "mongo:latest"
    ports:
    - "27017:27017"