version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/roselmamendes/o-q-le-agora
    steps:
      - checkout
      - run:
          name: Instala dependencias
          command: go get -v -t -d ./...
  tests:
    working_directory: /go/src/github.com/roselmamendes/o-q-le-agora
    steps:
      - run:
          name: Executa testes
          command: go test

workflows:
 version: 2
 build_test:
   jobs:
     - build
     - tests:
         requires:
           - build